import { GridColDef, GridRowsProp } from "@mui/x-data-grid";

export const rows: GridRowsProp = [
  {
    id: 1,
    col1: "Anna Llorens",
    col4: "Hello",
    col2: "111",
    col3: "Testing col3",
    col5: "New",
  },
  {
    id: 2,
    col1: "Anna Llorens",
    col4: "DataGridPro",
    col2: "112",
    col3: "Testing col3",
    col5: "New",
  },
  {
    id: 3,
    col1: "Anna Llorens",
    col4: "MUI",
    col2: "333",
    col3: "Hola Antonio",
    col5: "New",
  },
  {
    id: 4,
    col1: "Anna Llorens",
    col4: "Random",
    col2: "112",
    col3: "Que tal",
    col5: "New",
  },
  {
    id: 5,
    col1: "Anna Llorens",
    col4: "Machine",
    col2: "123",
    col3: "Bar",
    col5: "In Progress",
  },
  {
    id: 6,
    col1: "Anna Llorens",
    col4: "Example",
    col2: "198",
    col3: "Random",
    col5: "In Progress",
  },
  {
    id: 7,
    col1: "Anna Llorens",
    col4: "Barcelona",
    col2: "334",
    col3: "Data",
    col5: "In Progress",
  },
  {
    id: 8,
    col1: "Anna Llorens",
    col4: "Example",
    col2: "220",
    col3: "Ipsum",
    col5: "New",
  },
  {
    id: 9,
    col1: "Anna Llorens",
    col4: "Example",
    col2: "435",
    col3: "Random",
    col5: "In Progress",
  },
  {
    id: 10,
    col1: "Anna Llorens",
    col4: "Example",
    col2: "890",
    col3: "Hello",
    col5: "New",
  },
  {
    id: 11,
    col1: "Anna Llorens",
    col4: "Machine",
    col2: "22",
    col3: "World",
    col5: "New",
  },
  {
    id: 12,
    col1: "Anna Llorens",
    col4: "Roses",
    col2: "World",
    col3: "Bar",
    col5: "New",
  },
  {
    id: 13,
    col1: "Anna Llorens",
    col4: "Roses",
    col2: "256",
    col3: "Ipsum",
    col5: "In Progress",
  },
  {
    id: 14,
    col1: "Anna Llorens",
    col4: "Roses",
    col2: "789",
    col3: "Data",
    col5: "New",
  },
  {
    id: 15,
    col1: "Anna Llorens",
    col4: "Machine",
    col2: "178",
    col3: "Lorem",
    col5: "New",
  },
  {
    id: 16,
    col1: "Anna Llorens",
    col4: "Sunset",
    col2: "Data",
    col3: "World",
    col5: "New",
  },
  {
    id: 17,
    col1: "Anna Llorens",
    col4: "Sunset",
    col2: "599",
    col3: "Foo",
    col5: "New",
  },
  {
    id: 18,
    col1: "Anna Llorens",
    col4: "Barcelona",
    col2: "23",
    col3: "Bar",
    col5: "In Progress",
  },
  {
    id: 19,
    col1: "Anna Llorens",
    col4: "Amazing",
    col2: "670",
    col3: "Hello",
    col5: "New",
  },
  {
    id: 20,
    col1: "Anna Llorens",
    col4: "Machine",
    col2: "Hello",
    col3: "Ipsum",
    col5: "New",
  },
  {
    id: 21,
    col1: "Anna Llorens",
    col4: "Sunset",
    col2: "234",
    col3: "Lorem",
    col5: "In Progress",
  },
  {
    id: 22,
    col1: "Anna Llorens",
    col4: "Example",
    col2: "567",
    col3: "Bar",
    col5: "Completed",
  },
  {
    id: 23,
    col1: "Anna Llorens",
    col4: "Example",
    col2: "58",
    col3: "Hello",
    col5: "Completed",
  },
  {
    id: 24,
    col1: "Anna Llorens",
    col4: "Barcelona",
    col2: "278",
    col3: "Foo",
    col5: "Completed",
  },
  {
    id: 25,
    col1: "Anna Llorens",
    col4: "Machine",
    col2: 1,
    col3: "Random",
    col5: "Completed",
  },
  {
    id: 26,
    col1: "Anna Llorens",
    col4: "Example",
    col2: 56,
    col3: "World",
    col5: "In Progress",
  },
  {
    id: 27,
    col1: "Anna Llorens",
    col4: "Amazing",
    col2: 333,
    col3: "Lorem",
    col5: "Completed",
  },
  {
    id: 28,
    col1: "Anna Llorens",
    col4: "Example",
    col2: "560",
    col3: "Hello",
    col5: "Completed",
  },
];

export const columns: GridColDef[] = [
  { field: "col1", headerName: "Customer", width: 150 },
  { field: "col2", headerName: "Order ID", width: 100 },
  { field: "col3", headerName: "Company", width: 150 },
  { field: "col4", headerName: "Creation date", width: 150 },
  { field: "col5", headerName: "Status", width: 150 },
];
